name: CI/CD Process for Serge

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - 'docker-compose.yml'
      - 'docker-compose.dev.yml'
      - '.github/ISSUE_TEMPLATE/*.yml'
      - '.github/dependabot.yml'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - 'docker-compose.yml'
      - 'docker-compose.dev.yml'
      - '.github/ISSUE_TEMPLATE/*.yml'
      - '.github/dependabot.yml'
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:
  lint-api-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install ./api
      - name: Install mypy
        run: pip install mypy
      - name: Install all types stubs
        run: pip install lxml-stubs pandas-stubs types-Pillow types-PyYAML types-annoy types-beautifulsoup4 types-google-cloud-ndb types-psycopg2 types-pyOpenSSL types-redis types-requests types-tqdm types-ujson
      - name: Run pyright
        uses: jakebailey/pyright-action@v1
        with:
          working-directory: "./api"
      - name: Run mypy
        run: mypy --ignore-missing-imports ./api
      - name: Run ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./api"
          args: "--verbose"
      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
          src: "./api"
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/nsarrazin/serge
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          target: release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
